### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by mhugo** [sanpii/estcequilyafirstjeudicettesemaine#1]
When trying to access estcequilyafirstjeudicettesemaine.fr:

<pre>16:16:32 ~$ wget http://estcequilyafirstjeudicettesemaine.fr/
--2016-02-05 16:16:39--  http://estcequilyafirstjeudicettesemaine.fr/
Résolution de estcequilyafirstjeudicettesemaine.fr (estcequilyafirstjeudicettesemaine.fr)... 91.121.180.148
Connexion vers estcequilyafirstjeudicettesemaine.fr (estcequilyafirstjeudicettesemaine.fr)|91.121.180.148|:80... connecté.
requête HTTP transmise, en attente de la réponse... 404 Not Found
2016-02-05 16:16:39 ERREUR 404: Not Found.
</pre>

**Comment by sanpii** [comment]
Thank you for your report.

It was a mistake in the nginx configuration.
